#:kivy 2.3.1

<ForgotPasswordScreen>:
    name: "forgot_password"
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 20

        Label:
            text: "Forgot Password"
            font_size: 24

        TextInput:
            id: email_input
            hint_text: "Enter your email"

        Button:
            text: "Send OTP"
            on_release: root.send_reset_link(root.ids.email_input.text)

        Button:
            text: "Back to Login"
            on_release: app.root.current = "home"

        Label:
            id: status_label
            text: ""
            color: 1, 0, 0, 1  # Red for error messages
