#:kivy 2.3.1
<ResetPasswordScreen>:
    name: "reset_password"
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 20

        Label:
            text: "Reset Password"
            font_size: 24

        TextInput:
            id: otp_input
            hint_text: "Enter OTP"

        TextInput:
            id: new_password_input
            hint_text: "Enter New Password"
            password: True

        Button:
            text: "Reset Password"
            on_release: 
                root.reset_password(
                root.ids.otp_input.text,
                root.ids.new_password_input.text
                )

        Label:
            id: status_label
            text: ""
            color: 1, 0, 0, 1  # Red for error messages
