#:kivy 2.3.1

<ResetPasswordScreen>:
    name: "reset_password"

    MDBoxLayout:
        orientation: "vertical"
        spacing: 30
        padding: [20, 50, 20, 20]

        MDLabel:
            text: "Reset Password"
            font_style: "H4"
            halign: "center"
            theme_text_color: "Custom"
            text_color: [0.2, 0.6, 0.8, 1]

        MDTextField:
            id: otp_input
            hint_text: "Enter OTP"
            helper_text: "The OTP sent to your email"
            helper_text_mode: "on_focus"
            icon_left: "key-outline"
            size_hint_x: 0.8
            pos_hint: {"center_x": 0.5}

        MDTextField:
            id: new_password_input
            hint_text: "Enter New Password"
            helper_text: "Choose a strong password"
            helper_text_mode: "on_focus"
            password: True
            icon_left: "lock-outline"
            size_hint_x: 0.8
            pos_hint: {"center_x": 0.5}

        MDTextField:
            id: confirm_password_input
            hint_text: "Confirm New Password"
            helper_text: "Re-enter your password"
            helper_text_mode: "on_focus"
            password: True
            icon_left: "lock-outline"
            size_hint_x: 0.8
            pos_hint: {"center_x": 0.5}

        MDRaisedButton:
            text: "Reset Password"
            icon: "lock-reset"
            size_hint: None, None
            size: dp(200), dp(50)
            pos_hint: {"center_x": 0.5}
            md_bg_color: [0.2, 0.6, 0.8, 1]
            text_color: [1, 1, 1, 1]
            on_release: 
                root.reset_password(
                root.ids.otp_input.text,
                root.ids.new_password_input.text,
                root.ids.confirm_password_input.text
                )
